package cn.blog.dao;

import cn.blog.domain.Sort;
import cn.blog.domain.SortExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface SortMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sort
     *
     * @mbg.generated Fri Nov 27 19:46:20 CST 2020
     */
    long countByExample(SortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sort
     *
     * @mbg.generated Fri Nov 27 19:46:20 CST 2020
     */
    int deleteByExample(SortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sort
     *
     * @mbg.generated Fri Nov 27 19:46:20 CST 2020
     */
    int deleteByPrimaryKey(Integer sortId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sort
     *
     * @mbg.generated Fri Nov 27 19:46:20 CST 2020
     */
    int insert(Sort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sort
     *
     * @mbg.generated Fri Nov 27 19:46:20 CST 2020
     */
    int insertSelective(Sort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sort
     *
     * @mbg.generated Fri Nov 27 19:46:20 CST 2020
     */
    List<Sort> selectByExample(SortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sort
     *
     * @mbg.generated Fri Nov 27 19:46:20 CST 2020
     */
    Sort selectByPrimaryKey(Integer sortId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sort
     *
     * @mbg.generated Fri Nov 27 19:46:20 CST 2020
     */
    int updateByExampleSelective(@Param("record") Sort record, @Param("example") SortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sort
     *
     * @mbg.generated Fri Nov 27 19:46:20 CST 2020
     */
    int updateByExample(@Param("record") Sort record, @Param("example") SortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sort
     *
     * @mbg.generated Fri Nov 27 19:46:20 CST 2020
     */
    int updateByPrimaryKeySelective(Sort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sort
     *
     * @mbg.generated Fri Nov 27 19:46:20 CST 2020
     */
    int updateByPrimaryKey(Sort record);
}