package cn.blog.domain;

import java.util.Date;

public class Admin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.user_id
     *
     * @mbg.generated Fri Nov 27 19:59:03 CST 2020
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.user_name
     *
     * @mbg.generated Fri Nov 27 19:59:03 CST 2020
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.user_password
     *
     * @mbg.generated Fri Nov 27 19:59:03 CST 2020
     */
    private String userPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.user_nickname
     *
     * @mbg.generated Fri Nov 27 19:59:03 CST 2020
     */
    private String userNickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.user_avatar
     *
     * @mbg.generated Fri Nov 27 19:59:03 CST 2020
     */
    private String userAvatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.user_email
     *
     * @mbg.generated Fri Nov 27 19:59:03 CST 2020
     */
    private String userEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.user_birthday
     *
     * @mbg.generated Fri Nov 27 19:59:03 CST 2020
     */
    private Date userBirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.user_last_login_ip
     *
     * @mbg.generated Fri Nov 27 19:59:03 CST 2020
     */
    private String userLastLoginIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.user_last_login_time
     *
     * @mbg.generated Fri Nov 27 19:59:03 CST 2020
     */
    private Date userLastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.question1
     *
     * @mbg.generated Fri Nov 27 19:59:03 CST 2020
     */
    private String question1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.question2
     *
     * @mbg.generated Fri Nov 27 19:59:03 CST 2020
     */
    private String question2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.question3
     *
     * @mbg.generated Fri Nov 27 19:59:03 CST 2020
     */
    private String question3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.answer1
     *
     * @mbg.generated Fri Nov 27 19:59:03 CST 2020
     */
    private String answer1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.answer2
     *
     * @mbg.generated Fri Nov 27 19:59:03 CST 2020
     */
    private String answer2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.answer3
     *
     * @mbg.generated Fri Nov 27 19:59:03 CST 2020
     */
    private String answer3;

    public Admin(Integer userId, String userName, String userPassword, String userNickname, String userAvatar, String userEmail, Date userBirthday, String userLastLoginIp, Date userLastLoginTime, String question1, String question2, String question3, String answer1, String answer2, String answer3) {
        this.userId = userId;
        this.userName = userName;
        this.userPassword = userPassword;
        this.userNickname = userNickname;
        this.userAvatar = userAvatar;
        this.userEmail = userEmail;
        this.userBirthday = userBirthday;
        this.userLastLoginIp = userLastLoginIp;
        this.userLastLoginTime = userLastLoginTime;
        this.question1 = question1;
        this.question2 = question2;
        this.question3 = question3;
        this.answer1 = answer1;
        this.answer2 = answer2;
        this.answer3 = answer3;
    }

    public Admin() {
    }

    @Override
    public String toString() {
        return "Admin{" +
                "userId=" + userId +
                ", userName='" + userName + '\'' +
                ", userPassword='" + userPassword + '\'' +
                ", userNickname='" + userNickname + '\'' +
                ", userAvatar='" + userAvatar + '\'' +
                ", userEmail='" + userEmail + '\'' +
                ", userBirthday=" + userBirthday +
                ", userLastLoginIp='" + userLastLoginIp + '\'' +
                ", userLastLoginTime=" + userLastLoginTime +
                ", question1='" + question1 + '\'' +
                ", question2='" + question2 + '\'' +
                ", question3='" + question3 + '\'' +
                ", answer1='" + answer1 + '\'' +
                ", answer2='" + answer2 + '\'' +
                ", answer3='" + answer3 + '\'' +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.user_id
     *
     * @return the value of admin.user_id
     * @mbg.generated Fri Nov 27 19:59:03 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.user_id
     *
     * @param userId the value for admin.user_id
     * @mbg.generated Fri Nov 27 19:59:03 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.user_name
     *
     * @return the value of admin.user_name
     * @mbg.generated Fri Nov 27 19:59:03 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.user_name
     *
     * @param userName the value for admin.user_name
     * @mbg.generated Fri Nov 27 19:59:03 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.user_password
     *
     * @return the value of admin.user_password
     * @mbg.generated Fri Nov 27 19:59:03 CST 2020
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.user_password
     *
     * @param userPassword the value for admin.user_password
     * @mbg.generated Fri Nov 27 19:59:03 CST 2020
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.user_nickname
     *
     * @return the value of admin.user_nickname
     * @mbg.generated Fri Nov 27 19:59:03 CST 2020
     */
    public String getUserNickname() {
        return userNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.user_nickname
     *
     * @param userNickname the value for admin.user_nickname
     * @mbg.generated Fri Nov 27 19:59:03 CST 2020
     */
    public void setUserNickname(String userNickname) {
        this.userNickname = userNickname == null ? null : userNickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.user_avatar
     *
     * @return the value of admin.user_avatar
     * @mbg.generated Fri Nov 27 19:59:03 CST 2020
     */
    public String getUserAvatar() {
        return userAvatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.user_avatar
     *
     * @param userAvatar the value for admin.user_avatar
     * @mbg.generated Fri Nov 27 19:59:03 CST 2020
     */
    public void setUserAvatar(String userAvatar) {
        this.userAvatar = userAvatar == null ? null : userAvatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.user_email
     *
     * @return the value of admin.user_email
     * @mbg.generated Fri Nov 27 19:59:03 CST 2020
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.user_email
     *
     * @param userEmail the value for admin.user_email
     * @mbg.generated Fri Nov 27 19:59:03 CST 2020
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.user_birthday
     *
     * @return the value of admin.user_birthday
     * @mbg.generated Fri Nov 27 19:59:03 CST 2020
     */
//    public String getUserBirthday() {
//        return Utils.formatDate(userBirthday);
//    }
    public Date getUserBirthday() {
        return userBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.user_birthday
     *
     * @param userBirthday the value for admin.user_birthday
     * @mbg.generated Fri Nov 27 19:59:03 CST 2020
     */
    public void setUserBirthday(Date userBirthday) {
        this.userBirthday = userBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.user_last_login_ip
     *
     * @return the value of admin.user_last_login_ip
     * @mbg.generated Fri Nov 27 19:59:03 CST 2020
     */
    public String getUserLastLoginIp() {
        return userLastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.user_last_login_ip
     *
     * @param userLastLoginIp the value for admin.user_last_login_ip
     * @mbg.generated Fri Nov 27 19:59:03 CST 2020
     */
    public void setUserLastLoginIp(String userLastLoginIp) {
        this.userLastLoginIp = userLastLoginIp == null ? null : userLastLoginIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.user_last_login_time
     *
     * @return the value of admin.user_last_login_time
     * @mbg.generated Fri Nov 27 19:59:03 CST 2020
     */
    public Date getUserLastLoginTime() {
        return userLastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.user_last_login_time
     *
     * @param userLastLoginTime the value for admin.user_last_login_time
     * @mbg.generated Fri Nov 27 19:59:03 CST 2020
     */
    public void setUserLastLoginTime(Date userLastLoginTime) {
        this.userLastLoginTime = userLastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.question1
     *
     * @return the value of admin.question1
     * @mbg.generated Fri Nov 27 19:59:03 CST 2020
     */
    public String getQuestion1() {
        return question1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.question1
     *
     * @param question1 the value for admin.question1
     * @mbg.generated Fri Nov 27 19:59:03 CST 2020
     */
    public void setQuestion1(String question1) {
        this.question1 = question1 == null ? null : question1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.question2
     *
     * @return the value of admin.question2
     * @mbg.generated Fri Nov 27 19:59:03 CST 2020
     */
    public String getQuestion2() {
        return question2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.question2
     *
     * @param question2 the value for admin.question2
     * @mbg.generated Fri Nov 27 19:59:03 CST 2020
     */
    public void setQuestion2(String question2) {
        this.question2 = question2 == null ? null : question2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.question3
     *
     * @return the value of admin.question3
     * @mbg.generated Fri Nov 27 19:59:03 CST 2020
     */
    public String getQuestion3() {
        return question3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.question3
     *
     * @param question3 the value for admin.question3
     * @mbg.generated Fri Nov 27 19:59:03 CST 2020
     */
    public void setQuestion3(String question3) {
        this.question3 = question3 == null ? null : question3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.answer1
     *
     * @return the value of admin.answer1
     * @mbg.generated Fri Nov 27 19:59:03 CST 2020
     */
    public String getAnswer1() {
        return answer1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.answer1
     *
     * @param answer1 the value for admin.answer1
     * @mbg.generated Fri Nov 27 19:59:03 CST 2020
     */
    public void setAnswer1(String answer1) {
        this.answer1 = answer1 == null ? null : answer1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.answer2
     *
     * @return the value of admin.answer2
     * @mbg.generated Fri Nov 27 19:59:03 CST 2020
     */
    public String getAnswer2() {
        return answer2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.answer2
     *
     * @param answer2 the value for admin.answer2
     * @mbg.generated Fri Nov 27 19:59:03 CST 2020
     */
    public void setAnswer2(String answer2) {
        this.answer2 = answer2 == null ? null : answer2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.answer3
     *
     * @return the value of admin.answer3
     * @mbg.generated Fri Nov 27 19:59:03 CST 2020
     */
    public String getAnswer3() {
        return answer3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.answer3
     *
     * @param answer3 the value for admin.answer3
     * @mbg.generated Fri Nov 27 19:59:03 CST 2020
     */
    public void setAnswer3(String answer3) {
        this.answer3 = answer3 == null ? null : answer3.trim();
    }
}