package cn.blog.domain;

import java.util.Date;

public class Article {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_id
     *
     * @mbg.generated Fri Nov 27 20:09:41 CST 2020
     */
    private Integer articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_user_id
     *
     * @mbg.generated Fri Nov 27 20:09:41 CST 2020
     */
    private Integer articleUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_title
     *
     * @mbg.generated Fri Nov 27 20:09:41 CST 2020
     */
    private String articleTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_content
     *
     * @mbg.generated Fri Nov 27 20:09:41 CST 2020
     */
    private String articleContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_sort_id
     *
     * @mbg.generated Fri Nov 27 20:09:41 CST 2020
     */
    private Integer articleSortId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_tag_id
     *
     * @mbg.generated Fri Nov 27 20:09:41 CST 2020
     */
    private Integer articleTagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_date
     *
     * @mbg.generated Fri Nov 27 20:09:41 CST 2020
     */
    private Date articleDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_views_count
     *
     * @mbg.generated Fri Nov 27 20:09:41 CST 2020
     */
    private Integer articleViewsCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_like_count
     *
     * @mbg.generated Fri Nov 27 20:09:41 CST 2020
     */
    private Integer articleLikeCount;

    public Article(Integer articleId, Integer articleUserId, String articleTitle, String articleContent, Integer articleSortId, Integer articleTagId, Date articleDate, Integer articleViewsCount, Integer articleLikeCount) {
        this.articleId = articleId;
        this.articleUserId = articleUserId;
        this.articleTitle = articleTitle;
        this.articleContent = articleContent;
        this.articleSortId = articleSortId;
        this.articleTagId = articleTagId;
        this.articleDate = articleDate;
        this.articleViewsCount = articleViewsCount;
        this.articleLikeCount = articleLikeCount;
    }

    public Article() {
    }

    @Override
    public String toString() {
        return "Article{" +
                "articleId=" + articleId +
                ", articleUserId=" + articleUserId +
                ", articleTitle='" + articleTitle + '\'' +
                ", articleContent='" + articleContent + '\'' +
                ", articleSortId=" + articleSortId +
                ", articleTagId=" + articleTagId +
                ", articleDate=" + articleDate +
                ", articleViewsCount=" + articleViewsCount +
                ", articleLikeCount=" + articleLikeCount +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_id
     *
     * @return the value of article.article_id
     * @mbg.generated Fri Nov 27 20:09:41 CST 2020
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_id
     *
     * @param articleId the value for article.article_id
     * @mbg.generated Fri Nov 27 20:09:41 CST 2020
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_user_id
     *
     * @return the value of article.article_user_id
     * @mbg.generated Fri Nov 27 20:09:41 CST 2020
     */
    public Integer getArticleUserId() {
        return articleUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_user_id
     *
     * @param articleUserId the value for article.article_user_id
     * @mbg.generated Fri Nov 27 20:09:41 CST 2020
     */
    public void setArticleUserId(Integer articleUserId) {
        this.articleUserId = articleUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_title
     *
     * @return the value of article.article_title
     * @mbg.generated Fri Nov 27 20:09:41 CST 2020
     */
    public String getArticleTitle() {
        return articleTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_title
     *
     * @param articleTitle the value for article.article_title
     * @mbg.generated Fri Nov 27 20:09:41 CST 2020
     */
    public void setArticleTitle(String articleTitle) {
        this.articleTitle = articleTitle == null ? null : articleTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_content
     *
     * @return the value of article.article_content
     * @mbg.generated Fri Nov 27 20:09:41 CST 2020
     */
    public String getArticleContent() {
        return articleContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_content
     *
     * @param articleContent the value for article.article_content
     * @mbg.generated Fri Nov 27 20:09:41 CST 2020
     */
    public void setArticleContent(String articleContent) {
        this.articleContent = articleContent == null ? null : articleContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_sort_id
     *
     * @return the value of article.article_sort_id
     * @mbg.generated Fri Nov 27 20:09:41 CST 2020
     */
    public Integer getArticleSortId() {
        return articleSortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_sort_id
     *
     * @param articleSortId the value for article.article_sort_id
     * @mbg.generated Fri Nov 27 20:09:41 CST 2020
     */
    public void setArticleSortId(Integer articleSortId) {
        this.articleSortId = articleSortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_tag_id
     *
     * @return the value of article.article_tag_id
     * @mbg.generated Fri Nov 27 20:09:41 CST 2020
     */
    public Integer getArticleTagId() {
        return articleTagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_tag_id
     *
     * @param articleTagId the value for article.article_tag_id
     * @mbg.generated Fri Nov 27 20:09:41 CST 2020
     */
    public void setArticleTagId(Integer articleTagId) {
        this.articleTagId = articleTagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_date
     *
     * @return the value of article.article_date
     * @mbg.generated Fri Nov 27 20:09:41 CST 2020
     */
    public Date getArticleDate() {
        return articleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_date
     *
     * @param articleDate the value for article.article_date
     * @mbg.generated Fri Nov 27 20:09:41 CST 2020
     */
    public void setArticleDate(Date articleDate) {
        this.articleDate = articleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_views_count
     *
     * @return the value of article.article_views_count
     * @mbg.generated Fri Nov 27 20:09:41 CST 2020
     */
    public Integer getArticleViewsCount() {
        return articleViewsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_views_count
     *
     * @param articleViewsCount the value for article.article_views_count
     * @mbg.generated Fri Nov 27 20:09:41 CST 2020
     */
    public void setArticleViewsCount(Integer articleViewsCount) {
        this.articleViewsCount = articleViewsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_like_count
     *
     * @return the value of article.article_like_count
     * @mbg.generated Fri Nov 27 20:09:41 CST 2020
     */
    public Integer getArticleLikeCount() {
        return articleLikeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_like_count
     *
     * @param articleLikeCount the value for article.article_like_count
     * @mbg.generated Fri Nov 27 20:09:41 CST 2020
     */
    public void setArticleLikeCount(Integer articleLikeCount) {
        this.articleLikeCount = articleLikeCount;
    }
}