package cn.blog.domain;

import java.util.Date;

public class Comment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_id
     *
     * @mbg.generated Fri Nov 27 19:46:20 CST 2020
     */
    private Integer commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_time
     *
     * @mbg.generated Fri Nov 27 19:46:20 CST 2020
     */
    private Date commentTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_sub_id
     *
     * @mbg.generated Fri Nov 27 19:46:20 CST 2020
     */
    private Integer commentSubId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_user_id
     *
     * @mbg.generated Fri Nov 27 19:46:20 CST 2020
     */
    private Integer commentUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_nickname
     *
     * @mbg.generated Fri Nov 27 19:46:20 CST 2020
     */
    private String commentNickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_article_id
     *
     * @mbg.generated Fri Nov 27 19:46:20 CST 2020
     */
    private Integer commentArticleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_email
     *
     * @mbg.generated Fri Nov 27 19:46:20 CST 2020
     */
    private String commentEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_content
     *
     * @mbg.generated Fri Nov 27 19:46:20 CST 2020
     */
    private String commentContent;

    public Comment(Integer commentId, Date commentTime, Integer commentSubId, Integer commentUserId, String commentNickname, Integer commentArticleId, String commentEmail, String commentContent) {
        this.commentId = commentId;
        this.commentTime = commentTime;
        this.commentSubId = commentSubId;
        this.commentUserId = commentUserId;
        this.commentNickname = commentNickname;
        this.commentArticleId = commentArticleId;
        this.commentEmail = commentEmail;
        this.commentContent = commentContent;
    }

    public Comment() {
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_id
     *
     * @return the value of comment.comment_id
     * @mbg.generated Fri Nov 27 19:46:20 CST 2020
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_id
     *
     * @param commentId the value for comment.comment_id
     * @mbg.generated Fri Nov 27 19:46:20 CST 2020
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_time
     *
     * @return the value of comment.comment_time
     * @mbg.generated Fri Nov 27 19:46:20 CST 2020
     */
    public Date getCommentTime() {
        return commentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_time
     *
     * @param commentTime the value for comment.comment_time
     * @mbg.generated Fri Nov 27 19:46:20 CST 2020
     */
    public void setCommentTime(Date commentTime) {
        this.commentTime = commentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_sub_id
     *
     * @return the value of comment.comment_sub_id
     * @mbg.generated Fri Nov 27 19:46:20 CST 2020
     */
    public Integer getCommentSubId() {
        return commentSubId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_sub_id
     *
     * @param commentSubId the value for comment.comment_sub_id
     * @mbg.generated Fri Nov 27 19:46:20 CST 2020
     */
    public void setCommentSubId(Integer commentSubId) {
        this.commentSubId = commentSubId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_user_id
     *
     * @return the value of comment.comment_user_id
     * @mbg.generated Fri Nov 27 19:46:20 CST 2020
     */
    public Integer getCommentUserId() {
        return commentUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_user_id
     *
     * @param commentUserId the value for comment.comment_user_id
     * @mbg.generated Fri Nov 27 19:46:20 CST 2020
     */
    public void setCommentUserId(Integer commentUserId) {
        this.commentUserId = commentUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_nickname
     *
     * @return the value of comment.comment_nickname
     * @mbg.generated Fri Nov 27 19:46:20 CST 2020
     */
    public String getCommentNickname() {
        return commentNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_nickname
     *
     * @param commentNickname the value for comment.comment_nickname
     * @mbg.generated Fri Nov 27 19:46:20 CST 2020
     */
    public void setCommentNickname(String commentNickname) {
        this.commentNickname = commentNickname == null ? null : commentNickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_article_id
     *
     * @return the value of comment.comment_article_id
     * @mbg.generated Fri Nov 27 19:46:20 CST 2020
     */
    public Integer getCommentArticleId() {
        return commentArticleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_article_id
     *
     * @param commentArticleId the value for comment.comment_article_id
     * @mbg.generated Fri Nov 27 19:46:20 CST 2020
     */
    public void setCommentArticleId(Integer commentArticleId) {
        this.commentArticleId = commentArticleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_email
     *
     * @return the value of comment.comment_email
     * @mbg.generated Fri Nov 27 19:46:20 CST 2020
     */
    public String getCommentEmail() {
        return commentEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_email
     *
     * @param commentEmail the value for comment.comment_email
     * @mbg.generated Fri Nov 27 19:46:20 CST 2020
     */
    public void setCommentEmail(String commentEmail) {
        this.commentEmail = commentEmail == null ? null : commentEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_content
     *
     * @return the value of comment.comment_content
     * @mbg.generated Fri Nov 27 19:46:20 CST 2020
     */
    public String getCommentContent() {
        return commentContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_content
     *
     * @param commentContent the value for comment.comment_content
     * @mbg.generated Fri Nov 27 19:46:20 CST 2020
     */
    public void setCommentContent(String commentContent) {
        this.commentContent = commentContent == null ? null : commentContent.trim();
    }
}