package cn.blog.domain;

public class Sort {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sort.sort_id
     *
     * @mbg.generated Fri Nov 27 19:46:20 CST 2020
     */
    private Integer sortId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sort.sort_name
     *
     * @mbg.generated Fri Nov 27 19:46:20 CST 2020
     */
    private String sortName;

    public Sort(Integer sortId, String sortName) {
        this.sortId = sortId;
        this.sortName = sortName;
    }

    public Sort() {
    }

    @Override
    public String toString() {
        return "Sort{" +
                "sortId=" + sortId +
                ", sortName='" + sortName + '\'' +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sort.sort_id
     *
     * @return the value of sort.sort_id
     * @mbg.generated Fri Nov 27 19:46:20 CST 2020
     */
    public Integer getSortId() {
        return sortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sort.sort_id
     *
     * @param sortId the value for sort.sort_id
     * @mbg.generated Fri Nov 27 19:46:20 CST 2020
     */
    public void setSortId(Integer sortId) {
        this.sortId = sortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sort.sort_name
     *
     * @return the value of sort.sort_name
     * @mbg.generated Fri Nov 27 19:46:20 CST 2020
     */
    public String getSortName() {
        return sortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sort.sort_name
     *
     * @param sortName the value for sort.sort_name
     * @mbg.generated Fri Nov 27 19:46:20 CST 2020
     */
    public void setSortName(String sortName) {
        this.sortName = sortName == null ? null : sortName.trim();
    }
}