package cn.blog.domain;

public class Tag {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.tag_id
     *
     * @mbg.generated Fri Nov 27 19:46:20 CST 2020
     */
    private Integer tagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.tag_name
     *
     * @mbg.generated Fri Nov 27 19:46:20 CST 2020
     */
    private String tagName;

    public Tag(Integer tagId, String tagName) {
        this.tagId = tagId;
        this.tagName = tagName;
    }

    public Tag() {
    }

    @Override
    public String toString() {
        return "Tag{" +
                "tagId=" + tagId +
                ", tagName='" + tagName + '\'' +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.tag_id
     *
     * @return the value of tag.tag_id
     * @mbg.generated Fri Nov 27 19:46:20 CST 2020
     */
    public Integer getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.tag_id
     *
     * @param tagId the value for tag.tag_id
     * @mbg.generated Fri Nov 27 19:46:20 CST 2020
     */
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.tag_name
     *
     * @return the value of tag.tag_name
     * @mbg.generated Fri Nov 27 19:46:20 CST 2020
     */
    public String getTagName() {
        return tagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.tag_name
     *
     * @param tagName the value for tag.tag_name
     * @mbg.generated Fri Nov 27 19:46:20 CST 2020
     */
    public void setTagName(String tagName) {
        this.tagName = tagName == null ? null : tagName.trim();
    }
}